[package]
org = "roland"
name = "gsheet_new_row_to_sfdc_new_record"
version = "0.1.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "googleapis_sheets"
version = "0.99.7"

[[dependency]]
org = "ballerinax"
name = "sfdc"
version = "2.1.7"
