[package]
org = "ballerinax"
name = "gsheet_new_row_to_sfdc_new_record"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "googleapis.sheets"
version = "0.99.8"

[[dependency]]
org = "ballerinax"
name = "sfdc"
version = "2.1.8"
